# ╭───────────────────────────────────────────────────────────────────────────╮
# │                               REQUIREMENTS                                │
# ╰───────────────────────────────────────────────────────────────────────────╯


name: 🔪 YouTube Snippet Download

on:
    # Run Via a webhook only
    workflow_dispatch:
      inputs:
        video_array_b64:
          description: 'Results array of videos to download'  
          required: true
        count:
            description: 'number of snippets per video to download'  
            required: true
        duration:
            description: 'duration around snippet to download'  
            required: true
        timestamps:
            description: '[Optional] Timestamps (csv in seconds. 6,9,240   etc..) to use'
        gdrive_folder:
            description: 'where to put the download in google drive'  
            required: true
        return_webhook:
          description: 'Make.com webhook to trigger on finish'
          required: true
    repository_dispatch:
      types: [youtube_search]

jobs:

  download-snippets:
    runs-on: ubuntu-latest

    steps:

    # ╭──────────────────────────────────────────────────────────────────────────╮
    # │                                                                          │░
    # │                           INSTALL DEPENDENCIES                           │░
    # │                                                                          │░
    # ╰░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░



    # ╭───────────────────────────────────────────────────────╮
    # │             Get the contents of this repo             │
    # ╰───────────────────────────────────────────────────────╯
    - name: Checkout repository
      uses: actions/checkout@v3



    # ╭───────────────────────────────────────────────────────╮
    # │                    Install YT-DLP                     │
    # ╰───────────────────────────────────────────────────────╯
    - name: Install yt-dlp
      run: sudo pip install yt-dlp


      
    # ╭───────────────────────────────────────────────────────╮
    # │                  Install rClone + MPV                 │
    # ╰───────────────────────────────────────────────────────╯
    - name: Install rClone
      run: |
        sudo apt update
        sudo apt install mpv rclone



    # ╭──────────────────────────────────────────────────────────────────────────╮
    # │                                                                          │░
    # │                 Download snippets from videos in search                  │░
    # │                                                                          │░
    # ╰░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

    - name: Run Snippet Downloader
      continue-on-error: true
      run: |

        echo ${{ github.event.inputs.video_array_b64 }} > results.b64
        cat results.b64 | base64 -d > results.json

        cat results.json | jq -c '.results[] | .video' | while read -r video; do

            video_id=$(echo "$video" | sed 's/^.*=//' | cut -d'&' -f1)
            echo "Download snippets for $video_id"
            
            command="./scripts/snippets/yt_snippets.sh --videoid $video_id --count ${{ github.event.inputs.count }} --duration ${{ github.event.inputs.duration }}"

            if [ -n "${{ github.event.inputs.timestamps }}" ]; then
                command+=" --timestamps ${{ github.event.inputs.timestamps }}"
            fi
            
            eval "$command"

        done

        ls -la



    # ╭──────────────────────────────────────────────────────────────────────────╮
    # │                                                                          │░
    # │                               GOOGLE DRIVE                               │░
    # │                                                                          │░
    # ╰░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
    


    - name: rclone copy result back to google drive
      run: | 
          echo "${{ secrets.RCLONE_CONF_B64 }}" | base64 --decode > rclone.conf
          mkdir videos
          mv *.mp4 videos
          rclone copy ./videos/ GDrive:${{ github.event.inputs.gdrive_folder }}/ --config rclone.conf 




    # ╭──────────────────────────────────────────────────────────────────────────╮
    # │                                                                          │░
    # │               Once the results are complete, send webhook                │░
    # │                                                                          │░
    # ╰░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░



    - name: Trigger Return Webhook
      continue-on-error: true
      run: |
        curl -X POST \
          -H "Content-Type: text/plain" \
          -d "${{ github.event.inputs.gdrive_folder }}" \
          ${{ github.event.inputs.return_webhook }}


    # ╭───────────────────────────────────────────────────────╮
    # │     DEBUGGER - Use to SSH into the Github Runner      │
    # ╰───────────────────────────────────────────────────────╯
    # SSH ----------------------
    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1
    # SSH ----------------------