# ╭───────────────────────────────────────────────────────────────────────────╮
# │                               REQUIREMENTS                                │
# ╰───────────────────────────────────────────────────────────────────────────╯
# ╭───────────────────────────────────────────────────────╮
# │                                                       │
# │                        Inputs                         │
# │                     - upper_limit                     │
# │                    - search_query                     │
# │                   - return_webhook                    │
# │                                                       │
# │                        Outputs                        │
# │              - JSON object of video IDs               │
# │                                                       │
# ╰───────────────────────────────────────────────────────╯

name: 📹 YouTube Search

on:
    # Run Via a webhook only
    workflow_dispatch:
      inputs:
        upper_limit:
          description: 'Number of videos to find'     
          required: true
        search_query:
          description: 'yt-dlp search'  
          required: true
        return_webhook:
          description: 'Make.com webhook to trigger on finish'
    repository_dispatch:
      types: [youtube_search]

jobs:

  fetch-videos:
    runs-on: ubuntu-latest

    steps:


    # ╭───────────────────────────────────────────────────────╮
    # │             Get the contents of this repo             │
    # ╰───────────────────────────────────────────────────────╯
    - name: Checkout repository
      uses: actions/checkout@v3


    # ╭───────────────────────────────────────────────────────╮
    # │                    Install YT-DLP                     │
    # ╰───────────────────────────────────────────────────────╯
    - name: Install yt-dlp
      run: sudo pip install yt-dlp


    # ╭───────────────────────────────────────────────────────╮
    # │          Do a search and return a JSON file            │
    # ╰───────────────────────────────────────────────────────╯
    - name: Do YouTube Search
      run: |    
        yt-dlp --flat-playlist -O id -I 1:${{ github.event.inputs.upper_limit }} "${{ github.event.inputs.search_query }}"  > results.txt
        jq -nR --arg url "https://www.youtube.com/watch?v=" '[inputs | {"video": ($url + .)}]' results.txt > results.json


    # ╭───────────────────────────────────────────────────────╮
    # │      Once the results are complete, send webhook      │
    # ╰───────────────────────────────────────────────────────╯
    # Use -H "Content-Type: application/json"  for JSON
    # --data-binary is used to stop \n newlines from being added to base64 string.
    - name: Trigger Return Webhook
      if: ${{ github.event.inputs.return_webhook }}
      run: |
        content=$( cat results.json )

        echo $content

        curl -X POST \
          -H "Content-Type: text/plain" \
          --data-binary "$content" \
          ${{ github.event.inputs.return_webhook }}


    # ╭───────────────────────────────────────────────────────╮
    # │     DEBUGGER - Use to SSH into the Github Runner      │
    # ╰───────────────────────────────────────────────────────╯
    # SSH ----------------------
    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1
    # SSH ----------------------