name: 🎢 Test Main

on:
    # Run Via a webhook only
    workflow_dispatch:
      inputs:
        config_b64:
          description: 'Base64 configuration for Video Constructor'     
          required: true


jobs:

    one:
        uses: ioroot/GithubAction_VideoContructor/.github/workflows/test-one.yml@master

    two:
        needs: one
        uses: ioroot/GithubAction_VideoContructor/.github/workflows/test-two.yml@master