name: 🎢 Test Main

on:
    # Run Via a webhook only
    workflow_dispatch:
      inputs:
        config_b64:
          description: 'Base64 configuration for Video Constructor'     
          required: true


jobs:

    one:
        uses: IORoot/GithubAction_VideoConstructor/.github/workflows/test-one.yaml@master

    two:
        needs: one
        uses: IORoot/GithubAction_VideoConstructor/.github/workflows/test-two.yaml@master